---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llm-monitor
spec:
  selector:
    matchLabels:
      app: llm-monitor
  endpoints:
    - port: metrics
      path: /
      interval: 30s
      scrapeTimeout: 10s
