---
apiVersion: monitoring.coreos.com/v1beta1
kind: AlertmanagerConfig
metadata:
  name: llm-alerting
spec:
  receivers:
    - name: default
      webhookConfigs:
        - url: 'https://el-llm-monitoring-listener-llm-monitoring.apps.prod.xxx.com/'
  route:
    matchers:
      - matchType: '='
        name: alertname
        value: llm-updown-alert
    receiver: default
