---
apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-monitoring-config
  labels:
    app: llm-monitoring
  
data:
  endpoints.json: |
    [
      {
        "url": "https://api.openai.com/v1",
        "token": "your_openai_api_key",
        "model": "gpt-4",
        "type": "openai"
      }
    ]