---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: llm-monitoring
spec:
  groups:
  - name: llm-monitoring.rules
    rules:
    - alert: llm-updown-alert
      annotations:
        message: '{{ $labels.name }} is down!'
      expr: llm_endpoint_status{name=~".*"} == 0
      for: 1m
      labels:
        severity: "critical"
